import type { Metadata } from "next";
import React from 'react'
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css';
import { Header } from "./components/Header";

export const metadata: Metadata = {
  title: "TelegramAdd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
